steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/Pradeep699/cicd-service.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/brilliant-scene-290913/hello-kubernetes1:latest','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/brilliant-scene-290913/hello-kubernetes1:latest']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - delete
  - deployment
  - hello-kubernetes1
  - --ignore-not-found
  #- 'set'
  #- 'image'
  #- 'deployment/hello-kubernetes1'
  - 'hello-kubernetes1=gcr.io/brilliant-scene-290913/hello-kubernetes1:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetes'
  args:
  #- run
  - run
  #- hello-kubernetes1-6859f9df98
  - hello-kubernetes1-6859f9df98-ldftr 
  #- hello-kubernetes1
  - --image=gcr.io/brilliant-scene-290913/hello-kubernetes1:latest
  env:
  - CLOUDSDK_COMPUTE_ZONE=us-central1
  - CLOUDSDK_CONTAINER_CLUSTER=kubernetes
  
  
 
   
  
